services:
  #----------------------------------------------------------------------------#
  #                                    NGINX                                   #
  #----------------------------------------------------------------------------#
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: services/nginx/
    ports:
      - 8443:443
      - 8080:80
    networks:
      - trancendence
    volumes:
      - certificate:/var/ssl_cert/
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      resources_microservice:
        condition: service_started
        restart: true
      error_microservice:
        condition: service_started
        restart: true
      page_microservice:
        condition: service_started
        restart: true
      misc_microservice:
        condition: service_started
        restart: true
      account_microservice:
        condition: service_started
        restart: true
      chat_microservice:
        condition: service_started
        restart: true
    restart: "always"

  #----------------------------------------------------------------------------#
  #                                    CERTIFICATE                             #
  #----------------------------------------------------------------------------#
  certificate:
    container_name: certificate
    image: certificate
    build:
      context: services/certificate/
    volumes:
      - certificate:/var/ssl_cert/
    networks:
      - trancendence
    restart: "no"

  #----------------------------------------------------------------------------#
  #                                    SERVER                                  #
  #----------------------------------------------------------------------------#

  resources_microservice:
    command: prod-resources
    container_name: resources_microservice
    image: resources_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://resources_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"

  error_microservice:
    command: prod-error
    container_name: error_microservice
    image: error_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://error_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"

  page_microservice:
    command: prod-page
    container_name: page_microservice
    image: page_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://page_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"

  misc_microservice:
    command: prod-misc
    container_name: misc_microservice
    image: misc_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://misc_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"

  account_microservice:
    command: prod-account
    container_name: account_microservice
    image: account_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://account_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"

  chat_microservice:
    command: prod-chat
    container_name: chat_microservice
    image: chat_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chat_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"

  remote_microservice:
    command: prod-remote
    container_name: remote_microservice
    image: remote_microservice
    build:
      context: services/server/
      target: prod
    env_file: "services/server/conf/secrets.env"
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - database:/var/db/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://remote_microservice:3000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 13
    restart: "always"
  #----------------------------------------------------------------------------#
  #                                    CLIENT                                  #
  #----------------------------------------------------------------------------#
  client:
    container_name: client
    image: client
    build:
      context: services/client/
      target: prod
      args:
        - NPM_I_ARGS=--production
    volumes:
      - www:/var/www
    networks:
      - trancendence

  #----------------------------------------------------------------------------#
  #                                    VOLUMES                                 #
  #----------------------------------------------------------------------------#

volumes:
  certificate:
    name: certificate
    driver: local
    driver_opts:
      device: ./data/certificate
      o: bind
      type: none
  www:
    # still need to be a volume in prod
    # (for instance if we keep pfp in it)
    name: www
    driver: local
    driver_opts:
      device: ./data/www
      o: bind
      type: none
  database:
    name: database
    driver: local
    driver_opts:
      device: ./data/db
      o: bind
      type: none

networks:
  trancendence:
    name: trancendence
    driver: bridge
